### ISSUE TITLE
Example doesnt work

### ISSUE THREAD

**Issue by payanthe** [mental32/spotify.py#3]
AttributeError: module 'spotify' has no attribute 'Client'

in searching example file

**Comment by mental32** [comment]
Could you send a traceback of the error and which example file this occurs in?

**Comment by payanthe** [comment]
Traceback (most recent call last):
  `File "C:/***/spot/spotify.py", line 2, in <module>
    import spotify
  File "C:\***\spot\spotify.py", line 4, in <module>
    client = spotify.Client('f5fa8cb****4dc2a31e81844720a1f9', '3b********3f441489c18395cb77892f')
AttributeError: module 'spotify' has no attribute 'Client'
`


in this example 
https://github.com/mental32/spotify.py/blob/master/examples/searching.py

**Comment by mental32** [comment]
Thanks! 

What version of the library are you running? `print(spotify.__version__)` or `pip3 show spotify` should be able to show you this.

also did you install it from pypi using pip or clone it from Github?

**Comment by payanthe** [comment]
i try both 
but terminal said Version: 0.3.0

**Comment by mental32** [comment]
You wouldn't happen to have a python file in the same directory named `spotify.py` would you? If you do then remove it (or rename it), as the file is preferred when importing rather than the actual lib.

I have tested pypi and Github, and have not been able to reproduce this issue, which makes me think its something specific to your environment.

**Comment by payanthe** [comment]
It works after renaming file . thank you
